name: Documentation

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    env:
      GKS_ENCODING: "utf8"
      GKSwstype: "100"
      DATADEPS_ALWAYS_ACCEPT: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; 
                Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Packages status
        run: julia --project=docs/ -e 'using Pkg; Pkg.status()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          # DOCUMENTER_KEY: ${{ secrets.COMPATHELPER_PRIV }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
